<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.P6luaII' shared service.

return $this->privates['.service_locator.P6luaII'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\InscriptController::Logform' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\InscriptController::form' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\InscriptController:Logform' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
    'App\\Controller\\InscriptController:form' => ['privates', '.service_locator.Txvqv4R', 'get_ServiceLocator_Txvqv4RService.php', true],
], [
    'App\\Controller\\InscriptController::Logform' => '?',
    'App\\Controller\\InscriptController::form' => '?',
    'App\\Controller\\InscriptController:Logform' => '?',
    'App\\Controller\\InscriptController:form' => '?',
]);
