<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.iH_E8Q6' shared service.

return $this->privates['.service_locator.iH_E8Q6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\InscriptController::form' => ['privates', '.service_locator.30QvLaR', 'get_ServiceLocator_30QvLaRService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\InscriptController:form' => ['privates', '.service_locator.30QvLaR', 'get_ServiceLocator_30QvLaRService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
], [
    'App\\Controller\\InscriptController::form' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\InscriptController:form' => '?',
    'App\\Controller\\SecurityController:login' => '?',
]);
