<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLhjOkf1\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLhjOkf1/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLhjOkf1.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLhjOkf1\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerLhjOkf1\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'LhjOkf1',
    'container.build_id' => 'cedf7da0',
    'container.build_time' => 1568044683,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLhjOkf1');
